### ISSUE TITLE
Allow run-time selection of the region

### ISSUE THREAD

**Issue by ggoodman** [exratione/cloudformation-deploy#1]
Firstly: Thank you. This library appears to be grossly under-appreciated and very well built.

I understand your perspective with respect to AWS secrets but in practice, I have found that it would be practical to be able to override the region at run-time. I've built a CLI that leverages your tool for infrastructure provisioning and the target region is a configurable parameter.

I've been able to get around the run-time configuration issue by deferring the loading of your lib, setting `process.env.AWS_REGION` as needed and then doing `require('cloudformation-deploy')`, however I don't think that is at all in the spirit of your work.

Hope to hear your thoughts,

Geoff

**Comment by exratione** [comment]
Yes, that's an annoying use case for AWS tooling created in the configure-the-environment-not-the-code model, where you want to run deployment `X` with AWS config `A` and deployment `Y` with AWS config `B` in the same environment.

You could `child_process.fork` a subprocess and change the `AWS_REGION` environment variable on the way into that, but what you are doing is probably more elegant, though less safe to later changes. The fork method would probably be my choice over configuring, assuming I wasn't constrained to accept these parameters already.

I have the vague recollection that setting `region` alone in the Node.js SDK via `config.update({ region: '' })` makes it complain that it doesn't have a key and secret, as it is now expecting to read from the configuration object: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

**Comment by ggoodman** [comment]
The problem with `AWS.config.update({});` is that by the time I can run it, `cloudformation-deploy` has already created an instance of `AWS.CloudFormation()` that appears to freeze the configuration at the time of instantiation (a good thing!).

What I was hoping to see was an approach where the `AWS.CloudFormation()` instantiation is deferred and when it is invoked, it would accept `new AWS.CloudFormation({region: options.region});`.

**Comment by exratione** [comment]
Ok. Since it wasn't too hard, I've rolled a new version with lazy client creation and the option to add `config.clientOptions` that is passed to the client constructor.

**Comment by ggoodman** [comment]
You're the man. :thumbsup:
