### ISSUE TITLE
confusion on delete stack behavior

### ISSUE THREAD

**Issue by mikedon** [exratione/cloudformation-deploy#3]
I'm trying to use this library in our CI environment.  Ideally I would want to issue an update stack request if the stack already exists.  Alternatively if it just deleted the stack and then re-created it then I could get by.  

Is this kind of thing currently supported?

**Comment by exratione** [comment]
No, updating existing stacks is not supported. It is purely and deliberately a create-delete workflow.

The workflow for replacement of an old stack with create-delete runs as follows:

- the library creates the new stack.
- then invokes the callback function you provide, in which you can do whatever is needed to switch resources to use the new stack.
- the library then deletes the old stack.

**Comment by mikedon** [comment]
Got it.  The issue with this is it assumes every resource within a stack is unique, otherwise creating the stack will fail. 

For example, my CF template creates an API Gateway API Key.  It fails when trying to create the new stack again because the key already exists.

**Comment by exratione** [comment]
Yes, there are definitely cases in AWS where it is painful to take the create-delete approach, just as there are others where running a stack update is a mystery box of strangeness and failure.

For the create-delete approach you have to ensure that every name identifier / resource is unique per stack, or created outside the process.

For example, it is pretty common to create an ELB in a separate stack and only create and destroy stacks with new ASGs that are added to the long-lasting ELB. Analogously you might have a secondary stack containing long-term resources that never need recreating, like the key, and just reference them in the stack you are creating and destroying.

**Comment by mikedon** [comment]
That's a really good point.  I shouldn't be recreating the API key anew each time.
